/**
 *
 * Problem 2: Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 *
 * @author Omar Mujahid
 *
 */
public class Problem2 {

    public static int evenFib(int limit) {

        int fib1 = 1;
        int fib2 = 2;
        int fib = fib1 + fib2;
        int evenSum = 2;

        while (fib < limit) {

            fib1 = fib2;
            fib2 = fib;
            fib = fib1 + fib2;

            if (fib % 2 == 0) {

                evenSum += fib;

            }

        }

        return evenSum;

    }

    public static void main(String[] args) {

        Problem2 p2 = new Problem2();

        int sum = p2.evenFib(4000000);

        System.out.println("The solution is: " + sum);

    }
}
