/**
 *
 * Problem 2: Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 *
 * @author Omar Mujahid
 */
public class Problem2 {

    public static int evenFib(int limit) {

        int sum = 2;
        int i = 3;
        int fib1;
        int fib2;
        int fib;

        while (i < limit) {

            fib1 = i - 1;
            System.out.println("Fib1: " + fib1);
            fib2 = i;

            System.out.println("Fib2: " + fib2);
            fib = fib1 + fib2;

            System.out.println("Fib: " + fib);
            System.out.println(fib % 2 == 0);

            try {
                Thread.sleep(10000);
            } catch (InterruptedException c) {
                c.printStackTrace();
            }

            if (fib % 2 == 0) {

                System.out.println("Sum: " + sum);
                sum += fib;

            }

            i++;

        }

        return sum;

    }
}
